apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pqwkl9p80-nodejs
  janus-idp.io/tekton: pqwkl9p80-nodejs
  backstage.io/kubernetes-id: pqwkl9p80-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pqwkl9p80-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
